// Code generated by "stringer -type=timeUnit"; DO NOT EDIT.

package gocron

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[seconds-1]
	_ = x[minutes-2]
	_ = x[hours-3]
	_ = x[days-4]
	_ = x[weeks-5]
}

const _timeUnit_name = "secondsminuteshoursdaysweeks"

var _timeUnit_index = [...]uint8{0, 7, 14, 19, 23, 28}

func (i timeUnit) String() string {
	i -= 1
	if i < 0 || i >= timeUnit(len(_timeUnit_index)-1) {
		return "timeUnit(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _timeUnit_name[_timeUnit_index[i]:_timeUnit_index[i+1]]
}
