// Code generated by MockGen. DO NOT EDIT.
// Source: job.go
//
// Generated by this command:
//
//	mockgen -source=job.go -destination=mocks/job.go -package=gocronmocks
//
// Package gocronmocks is a generated GoMock package.
package gocronmocks

import (
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockJobDefinition is a mock of JobDefinition interface.
type MockJobDefinition struct {
	ctrl     *gomock.Controller
	recorder *MockJobDefinitionMockRecorder
}

// MockJobDefinitionMockRecorder is the mock recorder for MockJobDefinition.
type MockJobDefinitionMockRecorder struct {
	mock *MockJobDefinition
}

// NewMockJobDefinition creates a new mock instance.
func NewMockJobDefinition(ctrl *gomock.Controller) *MockJobDefinition {
	mock := &MockJobDefinition{ctrl: ctrl}
	mock.recorder = &MockJobDefinitionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobDefinition) EXPECT() *MockJobDefinitionMockRecorder {
	return m.recorder
}

// setup mocks base method.
func (m *MockJobDefinition) setup(arg0 *internalJob, arg1 *time.Location) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "setup", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// setup indicates an expected call of setup.
func (mr *MockJobDefinitionMockRecorder) setup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "setup", reflect.TypeOf((*MockJobDefinition)(nil).setup), arg0, arg1)
}

// MockjobSchedule is a mock of jobSchedule interface.
type MockjobSchedule struct {
	ctrl     *gomock.Controller
	recorder *MockjobScheduleMockRecorder
}

// MockjobScheduleMockRecorder is the mock recorder for MockjobSchedule.
type MockjobScheduleMockRecorder struct {
	mock *MockjobSchedule
}

// NewMockjobSchedule creates a new mock instance.
func NewMockjobSchedule(ctrl *gomock.Controller) *MockjobSchedule {
	mock := &MockjobSchedule{ctrl: ctrl}
	mock.recorder = &MockjobScheduleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockjobSchedule) EXPECT() *MockjobScheduleMockRecorder {
	return m.recorder
}

// next mocks base method.
func (m *MockjobSchedule) next(lastRun time.Time) time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "next", lastRun)
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// next indicates an expected call of next.
func (mr *MockjobScheduleMockRecorder) next(lastRun any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "next", reflect.TypeOf((*MockjobSchedule)(nil).next), lastRun)
}

// MockJob is a mock of Job interface.
type MockJob struct {
	ctrl     *gomock.Controller
	recorder *MockJobMockRecorder
}

// MockJobMockRecorder is the mock recorder for MockJob.
type MockJobMockRecorder struct {
	mock *MockJob
}

// NewMockJob creates a new mock instance.
func NewMockJob(ctrl *gomock.Controller) *MockJob {
	mock := &MockJob{ctrl: ctrl}
	mock.recorder = &MockJobMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJob) EXPECT() *MockJobMockRecorder {
	return m.recorder
}

// ID mocks base method.
func (m *MockJob) ID() uuid.UUID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(uuid.UUID)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockJobMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockJob)(nil).ID))
}

// LastRun mocks base method.
func (m *MockJob) LastRun() (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastRun")
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastRun indicates an expected call of LastRun.
func (mr *MockJobMockRecorder) LastRun() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastRun", reflect.TypeOf((*MockJob)(nil).LastRun))
}

// Name mocks base method.
func (m *MockJob) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockJobMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockJob)(nil).Name))
}

// NextRun mocks base method.
func (m *MockJob) NextRun() (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextRun")
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextRun indicates an expected call of NextRun.
func (mr *MockJobMockRecorder) NextRun() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextRun", reflect.TypeOf((*MockJob)(nil).NextRun))
}

// Tags mocks base method.
func (m *MockJob) Tags() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tags")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Tags indicates an expected call of Tags.
func (mr *MockJobMockRecorder) Tags() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tags", reflect.TypeOf((*MockJob)(nil).Tags))
}
