on:
  push:
    branches:
      - v2
  pull_request:
    branches:
      - v2

name: formatting
jobs:
  check-sorted:
    name: check sorted
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: verify example_test.go
        run: |
          grep "^func [a-z-A-Z]" example_test.go | sort -c
