on:
  push:
    branches:
      - v2
  pull_request:
    branches:
      - v2

name: pre-commit
jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: "stable"
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Run pre-commit
        uses: pre-commit/[email protected]
